# Generated by Django 5.0.13 on 2025-03-27 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0003_alter_project_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
