# Generated by Django 5.0.13 on 2025-03-30 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0004_alter_client_active_alter_client_deleted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.SmallIntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pay_days', to='foundation.project')),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'db_table': 'pay_day',
            },
        ),
    ]
