# Generated by Django 5.0.13 on 2025-04-01 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0005_payday'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('due_date', models.DateField()),
                ('payed', models.BooleanField(db_index=True, default=False)),
                ('payed_at', models.DateTimeField(null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='payments', to='foundation.project')),
            ],
            options={
                'db_table': 'payment',
            },
        ),
    ]
